### ISSUE TITLE
Nativescript app is not running with Firebase in IOS.

### ISSUE THREAD

**Issue by Vo0Do0** [EddyVerbruggen/nativescript-plugin-firebase#292] opened 2017-02-20 06:22 UTC
Hi,

I have integrated Firebase plugin with my nativescript app. I followed the instructions mentioned [Here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase). In android it is working fine but in IOS, it is building fine but while running it is giving  error like the following.

CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1165:18: Error in firebase.addChildEventListener: TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3491:32: EXCEPTION: Uncaught (in promise): TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3496:36: ORIGINAL STACKTRACE:
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3497:36: resolvePromise@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:416:40
file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:393:27
file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1166:13
ZoneAwarePromise@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:465:37
addValueEventListener@file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:1144:21
file:///app/shared/firebase-feed.service.js:24:43
subscribe@file:///app/tns_modules/rxjs/Observable.js:45:37
connect@file:///app/tns_modules/rxjs/observable/ConnectableObservable.js:37:27
call@file:///app/tns_modules/rxjs/observable/ConnectableObservable.js:101:56
subscribe@file:///app/tns_modules/rxjs/Observable.js:42:26
getFeedItems@file:///app/shared/question/question.component.js:32:23
ngOnInit@file:///app/shared/question/question.component.js:43:26
ngDoCheck
detectChangesInternal

Any help will be appretiated.

Thanks,

Soumen.

**Comment by anuragd7** [comment] 2017-02-24 11:01
+1

**Comment by anuragd7** [comment] 2017-02-24 15:19
Hi, 
I am also not able to run my ios project. The project runs fine in android but gives an error 

 Error in firebase.addChildEventListener: TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')

@EddyVerbruggen - Is there any fix for this?

Thanks

**Comment by EddyVerbruggen** [comment] 2017-03-12 11:26
Thanks for reporting. Closing as a dupe of #272. I'm going to post the proposed fix for that one shortly (version 3.10.2).

**Closed by EddyVerbruggen** 2017-03-12 11:26 UTC
Labels: bug, duplicate, iOS
