### ISSUE TITLE
JS: Error in firebase.init: Error: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist.

### ISSUE THREAD

**Issue by jiwonyune** [EddyVerbruggen/nativescript-plugin-firebase#59] opened 2016-06-19 16:45 UTC
Hi. 

I am having a trouble running the **angular-firebase** branch of **sample-groceries** (https://github.com/NativeScript/sample-Groceries/tree/angular-firebase). I checked out these two issues (https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/36 and https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/48), but I still cannot get it working. 

By the way, I also posted an issue here too (https://github.com/NativeScript/sample-Groceries/issues/104). If this is a problem, please let me know

This is what the console looks like:
`Successfully deployed on device with identifier 'ff144bbb'.
06-20 01:18:57.413 26107 26107 V GoogleSignatureVerifier: dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
JS: firebase.init done
JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE.
chromium: [INFO:library_loader_hooks.cc(144)] Chromium logging enabled: level = 0, default verbosity = 0
06-20 01:19:15.333 26577 26577 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
JS: Error in firebase.init: Error: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
JS:     com.google.firebase.FirebaseApp.getInstance(Unknown Source)
JS:     com.google.firebase.FirebaseApp.getInstance(Unknown Source)
JS:     com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
JS:     com.tns.Runtime.runModule(Native Method)
JS:     com.tns.Runtime.runModule(Runtime.java:241)
JS:     com.tns.Runtime.run(Runtime.java:235)
JS:     com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
JS:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
JS:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
JS:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
JS:     android.app.ActivityThread.access$1800(ActivityThread.java:221)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:158)
JS:     android.app.ActivityThread.main(ActivityThread.java:7224)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
JS: firebase.init error: Error: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
JS:     com.google.firebase.FirebaseApp.getInstance(Unknown Source)
JS:     com.google.firebase.FirebaseApp.getInstance(Unknown Source)
JS:     com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
JS:     com.tns.Runtime.runModule(Native Method)
JS:     com.tns.Runtime.runModule(Runtime.java:241)
JS:     com.tns.Runtime.run(Runtime.java:235)
JS:     com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
JS:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
JS:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
JS:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6316)
JS:     android.app.ActivityThread.access$1800(ActivityThread.java:221)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:158)
JS:     android.app.ActivityThread.main(ActivityThread.java:7224)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-20 01:19:21.413 26651 26651 V GoogleSignatureVerifier: dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
`

When I try to do the **sign up**, I get this:
`JS: --- auth state changed: com.google.android.gms.internal.zzadg@56469be
JS: --- user: null
JS: Logging in the user failed
JS: Error:
JS: Permission denied
JS: --- auth state changed: com.google.android.gms.internal.zzadg@56469be
JS: --- user: null
JS: Logging in the user failed
JS: Error:
JS: Permission denied
`

How can I fix this?

The following information may be redundant, but I'll post them anyways just in case.

**app.gradle**
`android {
  defaultConfig {
    applicationId "org.nativescript.groceries"
    multiDexEnabled true
    generatedDensities = []
  }
  aaptOptions {
    additionalParameters "--no-version-vectors"
  }
}`

**package.json**
`{
	"name": "Groceries",
	"version": "1.0.0",
	"description": "A NativeScript-built iOS and Android app for managing grocery lists",
	"repository": {
		"type": "git",
		"url": "https://github.com/nativescript/sample-Groceries.git"
	},
	"keywords": [
		"NativeScript"
	],
	"author": "TJ VanToll <tj.vantoll@gmail.com> (https://www.tjvantoll.com/)",
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/nativescript/sample-Groceries/issues"
	},
	"homepage": "https://github.com/nativescript/sample-Groceries/groceries",
	"nativescript": {
		"id": "org.nativescript.groceries",
		"tns-ios": {
			"version": "2.0.1"
		},
		"tns-android": {
			"version": "2.0.0"
		}
	},
	"dependencies": {
		"@angular/common": "2.0.0-rc.1",
		"@angular/compiler": "2.0.0-rc.1",
		"@angular/core": "2.0.0-rc.1",
		"@angular/http": "2.0.0-rc.1",
		"@angular/platform-browser": "2.0.0-rc.1",
		"@angular/platform-browser-dynamic": "2.0.0-rc.1",
		"@angular/platform-server": "2.0.0-rc.1",
		"@angular/router-deprecated": "2.0.0-rc.1",
		"email-validator": "^1.0.4",
		"nativescript-angular": "0.1.6",
		"nativescript-iqkeyboardmanager": "^1.0.1",
		"nativescript-plugin-firebase": "^3.0.1",
		"nativescript-social-share": "^1.1.3",
		"nativescript-unit-test-runner": "^0.3.3",
		"tns-core-modules": "2.0.0-angular-7"
	},
	"devDependencies": {
		"babel-traverse": "6.9.0",
		"babel-types": "6.10.0",
		"babylon": "6.8.1",
		"filewalker": "0.1.2",
		"jasmine-core": "^2.4.1",
		"karma": "^0.13.22",
		"karma-jasmine": "^1.0.2",
		"karma-nativescript-launcher": "^0.4.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.3.2",
		"typescript": "^1.8.10"
	}
}
`
**build.gradle**
` 
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
		    classpath "com.android.tools.build:gradle:1.5.0"
        classpath 'com.google.gms:google-services:3.0.0'
	  }
}

apply plugin: 'com.google.gms.google-services'
`

**google-services.json**
`
{
  "project_info": {
    "project_number": "1029306009568",
    "firebase_url": "https://test-fd26c.firebaseio.com",
    "project_id": "test-fd26c",
    "storage_bucket": "test-fd26c.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "**********************************************",
        "android_client_info": {
          "package_name": "org.nativescript.groceries"
        }
      },
      "oauth_client": [
        {
          "client_id": "**********************************************",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "**********************************************"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ],
  "configuration_version": "1"
}
`

Any help would be really appreciated. Thank a lot in advance.

**Comment by jlooper** [comment] 2016-06-19 17:04
This is a dupe of #104 on the sample-Groceries repo, we'll address it there.

**Closed** 2016-06-19 19:36 UTC

**Comment by mahendramahi** [comment] 2016-07-07 12:56
Please describe it properly that how can i remove this error ..... every time when i run my project FirebaseStorage.getInstace() gives null and exception illegal exception FirebaseApp with name [DEFAULT] doesn't exist

**Comment by EddyVerbruggen** [comment] 2016-07-07 14:16
@mahendramahi well, we [tried that](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#firebaseapp-with-name-default-doesnt-exist)
