### ISSUE TITLE
Is Firebase's Performance monitoring supported?

### ISSUE THREAD

**Issue by FatimahSanni** [EddyVerbruggen/nativescript-plugin-firebase#981] opened 2018-10-19 15:11 UTC
Hi,

I just wanted to find out if firebase's performance monitoring feature is supported by this plugin and how to go about it. It's not in the docs

Thanks

**Comment by EddyVerbruggen** [comment] 2018-10-19 18:17
Duplicate of #370.

**Closed by EddyVerbruggen** 2018-10-19 18:17 UTC
