### ISSUE TITLE
Unusual error message when retrieving data set and binding to layout

### ISSUE THREAD

**Issue by jlooper** [EddyVerbruggen/nativescript-plugin-firebase#272] opened 2017-01-31 03:00 UTC
hi, recently with the lastest plugin I have been getting this message `TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')` somewhat frequently when livesyncing and retrieving images from the database. Anyone else getting this? It blocks me from getting the data.

**Comment by jlooper** [comment] 2017-01-31 13:48
I've nailed down the type of layout that causes the issue: it's using ngFor to loop through a dataset bound to an observable. So oftentimes this piece throws that error:

```
<FlexboxLayout class="container" *ngFor="let yowl of (yowls$ | async)">
        <FlexboxLayout class="column">
            <Image src="~/images/k1" width="120" height="50"></Image>
        </FlexboxLayout>
        <FlexboxLayout class="column">
            <FlexboxLayout class="row">
                <Label class="bold" [text]="yowl.name"></Label>
                <Label class="small" [text]="'@'+yowl.username"></Label>
                <Label class="small" [text]='yowl.date | date:"ss"' fontSize="15"></Label>
            </FlexboxLayout>
            <FlexboxLayout class="row">
                <Label class="regular" textWrap="true" [text]="yowl.text"></Label>
            </FlexboxLayout>
            <FlexboxLayout class="row">
            <Button width="25%" [text]="'fa-mail-reply' | fonticon" class="fa grey"></Button>
            <Button width="25%" [text]="'fa-retweet' | fonticon" class="fa grey"></Button>
            <Button width="25%" [text]="'fa-heart' | fonticon" class="fa grey"></Button>
            <Button width="25%" [text]="'fa-envelope' | fonticon" class="fa grey"></Button>
        </FlexboxLayout>
        </FlexboxLayout>
    </FlexboxLayout>
```
Using a ListView seems more stable; any reason why this would be a problem, or perhaps it's an Angular issue?

**Comment by NordlingArt** [comment] 2017-02-02 21:48
I'm getting this error too. Cannot get past it. Using this simple line:

```js
firebase.query(function(snapshot) {
  console.log("Found categories:", !!snapshot.value);
}, "/categories", {
  singleEvent: true,
  orderBy: { type: firebase.QueryOrderByType.KEY }
});
```

Will throw the error:

```
Error in firebase.query: TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')
```

**Comment by jlooper** [comment] 2017-02-02 21:56
@NordlingArt is it an issue with 'snapshot', do you think?

**Comment by EddyVerbruggen** [comment] 2017-02-02 21:58
If 3.9.0 worked fine than my main suspect is [this line](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/063cc1d3b874efa3c6e8e8e07af816ce759c2f8b/firebase.ios.js#L494) - could you change it to `runInit()` and see if that makes a difference?

I was added because of Angular issues.

**Comment by NordlingArt** [comment] 2017-02-02 21:58
@jlooper - Not sure because I cannot console log ´snapshot´ at all.

**Comment by jlooper** [comment] 2017-02-02 22:17
I feel like that fix does make a difference, although I have trouble making this happen consistently. Let me try a few different projects. Crossing fingers!

**Comment by jlooper** [comment] 2017-02-02 22:21
I tried a second project and it does seem to work better. @NordlingArt can you try? 

Hope this fix won't do damage to the fix we made for push 

Thanks Eddy!

**Comment by EddyVerbruggen** [comment] 2017-02-02 22:24
Cool. It won't hurt push, but it may make your Angular app not work with Firebase. Unless you just proofed that wrong :) .. really depends on how you bootstrap Firebase though.

**Comment by jlooper** [comment] 2017-02-02 22:25
I sure hope it won't do that! Working on 3 apps right now using this stuff :D - look forward to not battling that ugly error :D thanks!

**Comment by NordlingArt** [comment] 2017-02-02 22:55
@jlooper - I could try but I'm not working with Angular so it should be working as it's always been doing :)

**Comment by jlooper** [comment] 2017-02-09 14:49
🔔 ping Eddy...I get this error consistently now with Firebase + Angular...hoping to sort it with the proposed change if it won't break other things

**Comment by EddyVerbruggen** [comment] 2017-02-09 15:09
@jlooper If I push it to this repo (not to npm), can you test?

**Comment by jlooper** [comment] 2017-02-10 15:46
@EddyVerbruggen yes, I think so - it will be testing using NNG - I can also check the ramifications for push

**Comment by EddyVerbruggen** [comment] 2017-02-10 15:49
Would be great!

**Comment by jlooper** [comment] 2017-02-16 20:10
at this point I have to make the edit each time I use firebase with angular....so I think we ought to make this change live...thanks Eddy!

**Comment by Vo0Do0** [comment] 2017-02-24 07:35
I was facing the same problem. After making the change in [this file](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/063cc1d3b874efa3c6e8e8e07af816ce759c2f8b/firebase.ios.js#L494) as specified by @EddyVerbruggen, I am getting a new errors. Here are the error messages.

**CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:498:18: Error in firebase.init: Error: Expecting function got: undefined
CONSOLE LOG file:///app/tns_modules/nativescript-plugin-firebase/firebase.js:498:18: Error in firebase.init: Error: Expecting function got: undefined
2017-02-24 12:46:16.753134 questNewS[251:7356] CONSOLE LOG file:///app/main.js:22:16: firebase.init done**

And

**JavaScript error:
2017-02-24 12:46:20.297377 questNewS[251:7356] file:///app/tns_modules/tns-core-modules/ui/core/view.js:96:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() ProxyViewContainer(65)
file:///app/tns_modules/tns-core-modules/ui/core/view.js:96:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() ProxyViewContainer(65)**

**Comment by kmuthukrishnan** [comment] 2017-02-24 15:20
@jlooper 
@EddyVerbruggen 

Iam facing the same error when trying to build my project in iOs (works in android). 

`Error in firebase.query: TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')`

Is this issue fixed or likely to be fixed soon? Help please, I would like to release my app, but this is proving to be a big block!

**Comment by anuragd7** [comment] 2017-02-24 15:23
Hi,
I am also not able to run my ios project. The project runs fine in android but gives an error

Error in firebase.addChildEventListener: TypeError: null is not an object (evaluating 'firebase.instance.childByAppendingPath')

@EddyVerbruggen - Is there any fix for this?

Thanks

**Comment by EddyVerbruggen** [comment] 2017-03-05 15:30
@anuragd7 @kmuthukrishnan I'd love to help you but I need something to reproduce the problem with. Either your project or (preferably) a minimal project that shows the error.

**Comment by jlooper** [comment] 2017-03-05 15:44
I see this with Angular projects- like github.com/jlooper/emoting in the NativeScript folder as a basic example. It's that timeout function. Is there a way around this via our code if we don't remove the timeout on init for iOS?

**Comment by EddyVerbruggen** [comment] 2017-03-05 15:50
Then the question to @anuragd7 @kmuthukrishnan should be: can you try with [the change I mentioned before](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/272#issuecomment-277097406) and see if that solves the problem?

**Comment by anuragd7** [comment] 2017-03-05 17:02
@EddyVerbruggen Thanks for the response. Yes we did try the change mentioned in the thread.  Will set up a minimal project to help replicate the error and share it with you.

**Comment by EddyVerbruggen** [comment] 2017-03-05 17:08
That would be great! So changing that line didn't make a difference?

**Comment by anuragd7** [comment] 2017-03-05 17:12
Yes. That's what I recollect. Don't have  the Mac with me right now so will
get back with more information tomorrow. Thanks

**Comment by anuragd7** [comment] 2017-03-06 07:07
@EddyVerbruggen, I just put together a sample project to share with you - but it seems to be running correctly in IOS - so I am trying to figure out what's causing the different behavior on the larger application. Will keep you posted. Thanks again for your offer to help.

**Comment by anuragd7** [comment] 2017-03-07 17:00
@EddyVerbruggen - can confirm that not facing this issue any more. The fix you have suggested works.

**Comment by jlooper** [comment] 2017-03-11 23:36
duped here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/292

**Comment by EddyVerbruggen** [comment] 2017-03-12 11:28
Thanks all, and thanks @anuragd7 for confirming as well. Fix added to 3.10.2.

**Closed by EddyVerbruggen** 2017-03-12 11:28 UTC
Labels: bug, iOS

**Comment by macismail2003** [comment] 2018-01-28 14:08
Hi @EddyVerbruggen 

I am facing the same issue even though I am in version "nativescript-plugin-firebase": "^5.1.4",

Please help, Thank you.
Seyed Ismail

**Comment by kushMehra** [comment] 2018-01-30 12:07
Hi @EddyVerbruggen 

I am getting the same error. Below is my package.json

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.id",
    "tns-android": {
      "version": "3.4.1"
    },
    "tns-ios": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "nativescript-angular": "~5.2.0",
    "nativescript-plugin-firebase": "^5.1.4",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.6.0",
    "typescript": "~2.6.2"
  }
}


and the code that is causing the error is below.

firebase.query(
            ()=>{},
            '/businessName',
            {
                singleEvent: true,
                orderBy:{
                    type: firebase.QueryOrderByType.CHILD
                }
            }
        ).then(
            (res=>{
                console.log("something should come here",res)
            })
        ).catch((res=>{
            console.log("does this give error?",res)}))

the actual error message is:

Error in firebase.query: TypeError: null is not an object (evaluating 'firebase_common_1.firebase.instance.childByAppendingPath')

Please help!

**Comment by EddyVerbruggen** [comment] 2018-01-30 12:11
@kushMehra Can you please add the import/require statement of `firebase` as well? And try formatting with 3 backtics like this:

```
` ` ` <-- remove the spaces  from this example
Your code here
` ` ` 
```

**Comment by kushMehra** [comment] 2018-01-30 12:29
```import firebase = require("nativescript-plugin-firebase");
```

**Comment by kushMehra** [comment] 2018-01-30 12:29
Here it is
```
import firebase = require("nativescript-plugin-firebase");
```

**Comment by EddyVerbruggen** [comment] 2018-01-30 13:38
Thanks! I've formatted your previous post as well - will try to take a look soon.

**Comment by EddyVerbruggen** [comment] 2018-01-30 14:41
@macismail2003 & @kushMehra: iOS/Android or both?

**Comment by EddyVerbruggen** [comment] 2018-01-30 16:47
Grab 5.1.5 and please open a **new** issue with a demo app if there's still a problem.

**Comment by kushMehra** [comment] 2018-01-30 20:37
Thanks Eddy, Im getting this on iOS. Haven't tried on android. Ill use the 5.1.5 tonight and get back to you.

**Comment by kushMehra** [comment] 2018-01-31 12:25
Thanks @EddyVerbruggen, it works!
Would you mind sharing what was the issue?

**Comment by EddyVerbruggen** [comment] 2018-01-31 12:37
@kushMehra That's great to hear! I think during livesync (or whatever triggered the issue) the `init` method is not invoked (before or at all) the `firebase.instance` property was accessed (it would be `undefined` in that case).

So I simply removed my custom `firebase.instance` cache as it's hardly better than grabbing the Firebase instance from the native SDK (which is never `undefined`).
