### ISSUE TITLE
Incorrect ordering while using `singleEvent` as `true`

### ISSUE THREAD

**Issue by Jai-Krish** [EddyVerbruggen/nativescript-plugin-firebase#405] opened 2017-06-22 14:00 UTC
Since setting `singleEvent` as `true` returns the whole set of data in a single response as a `value:Object` containing all the values
i.e `{key1:val1, key2:val2,...}` (existing behavior)
rather than `value:Array<Object>`
 i.e `[{key:key1, val:val1}, {key:key2, val:val2},...]` (expected behavior),
 the order becomes inconsistent while iterating through the result object.

**Comment by JillevdW** [comment] 2019-01-18 15:52
After a long adventure through the issues I believe this to be the cause of my problem.

When `singleEvent` is set to false, the callback is called for each item individually, in the right order. However, when it is set to true, it is returned all at once, it is returned in a seemingly random (looks like reverse alphabetical?) order.

Without having too much time to work through the code behind this that actually makes the firebase call, I'd say the solution would be to add the objects to an array instead of making them children of an object, and thus keeping the order as received from the database.

**Comment by EddyVerbruggen** [comment] 2019-01-18 16:08
As you can see [here for Android](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/6a0d221091ab22f2824a552eee95083c3d8ddb83/src/firebase.android.ts#L1644) and [here for iOS](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/fd48490680c78bc33f772c65ac9fc661c4880031/src/firebase.ios.ts#L1415), the data is simply returned as one "snapshot", and the plugin passes that to the client. So I don't really see how to implement those suggestions.

**Comment by JillevdW** [comment] 2019-01-18 16:14
Hey, thanks for the incredibly swift reply. I'm wondering if I got things confused then, I'll now refer to how I've implemented something similar in Swift:
`
mainRef.child("Posts").queryOrdered(byChild: "timestamp").queryLimited(toFirst: 100).observe(.value, with: { (snapshot) in
            if snapshot.exists() {
                for post in snapshot.children {
                    if let postSnap = post as? DataSnapshot {
                        // do something with postSnap
                    }
                }
            }
        })
`

In this code, the snapshot.children are sorted in the way declared by the query: ordered by the child called "timestamp". I can't get this to work with this plugin, so I'm wondering if the implementation behind the scenes differs from what this query does? Thanks for your time.

**Comment by JillevdW** [comment] 2019-01-18 17:40
@EddyVerbruggen that could be true, I'm not sure, however that would imply the query function is not the same as the function I just posted, some observations:
- In the Swift function, the snapshot function contains all the results from the query in an array. As such, the callback is only called **once** (not entirely true, since I use the function `.observe` which observes value changes as well, but it will still return all the items in one call, even on subsequent calls).
- `singleEvent` set to true returns all the results from the query bundled into an object.
- `singleEvent` set to false calls the callback once for every single item returned from the query.

So if what you say is correct, there is still a difference between the native behaviour and the way the interface here exposes them, perhaps *that* is not really relevant to anyone that hasn't used the native library, but it is relevant here since we lose the order of elements when using `singleEvent = true`.

**Comment by EddyVerbruggen** [comment] 2019-02-19 16:33
@JillevdW Looks like this is fixed in plugin version 8.0.0 (out soon). The order in the JSON object is now as specified as in the `orderBy` clause (on Android this was already the case), and I've added a new `children` property to the result object which is an array. Docs updated.

**Closed by EddyVerbruggen** 2019-02-19 16:33 UTC
