### ISSUE TITLE
firebase.getValue() is not a function

### ISSUE THREAD

**Issue by FrancoisGayraud** [EddyVerbruggen/nativescript-plugin-firebase#567] opened 2017-12-08 16:23 UTC
Hi,

I work with the 4.1.1 version of this plugin and I want to get a value in my database.
I have a  "TypeError: firebase.getValue() is not a function".

Any ideas?

**Comment by EddyVerbruggen** [comment] 2017-12-08 16:26
Duplicate of #556

**Closed by EddyVerbruggen** 2017-12-08 16:26 UTC
