### ISSUE TITLE
[Feature Request] the plugin should update the platform data automatically

### ISSUE THREAD

**Issue by giordy** [EddyVerbruggen/nativescript-plugin-firebase#180] opened 2016-10-17 11:02 UTC
Hello,

it would be great if the plugin could:

- include the google services plugin automatically in gradle, as mentioned in #102 
- copy the `google-services.json` file in `platform/android` and equivalent for iOS. The project `nativescript-i18n` is doing something similar, perhaps it is possible to reuse some code. 

Adding/removing platforms is not so uncommon during the day and manually editing is rather time consuming.

That said, thanks for the plugin ^^

**Comment by EddyVerbruggen** [comment] 2016-10-17 11:04
Dupe of #102.

If you have the skills to help with this it's highly appreciated.

**Closed by EddyVerbruggen** 2016-10-17 11:04 UTC

**Comment by giordy** [comment] 2016-10-17 11:06
@EddyVerbruggen I tried this morning a bit with gradle but I'm no expert either, unfortunately. Will try to investigate.

**Comment by EddyVerbruggen** [comment] 2016-10-17 11:07
Would be cool, please report anything (even failures) in #102. Ideally gradle would handle this, but an npm postinstall script wouldn't be the end of the world either.
