### ISSUE TITLE
Error TS1036: Statements are not allowed in ambient contexts.

### ISSUE THREAD

**Issue by anuragd7** [EddyVerbruggen/nativescript-plugin-firebase#686] opened 2018-04-26 16:39 UTC
Hi 
I have been using the plugin version 5.1.2 in my project and haven't faced any problems in a long time. Today I needed to rebuild the project after deleting Nodemodules, Hooks and platforms folder. 

After running `npm install` and` tns platform add ios`  I tried to build the IOS project at which time I got this error.
Would appreciate any pointers as to how I can fix this.
Thanks

```
NRMac$ tns build ios --clean
Executing before-prepare hook from /Users/NRMac/Projects/newquest/questNewS/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
app/services/firebase-auth.service.ts(374,14): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.

app/services/firebase-auth.service.ts(389,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.

app/services/firebase-auth.service.ts(397,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(405,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(413,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(421,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.

app/services/firebase-auth.service.ts(435,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(443,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(451,22): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-auth.service.ts(465,16): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/firebase-create.service.ts(692,18): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.
app/services/my-test.service.ts(756,14): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.

app/services/search-status.service.ts(91,14): error TS2339: Property 'analytics' does not exist on type 'typeof "/Users/NRMac/Projects/newquest/questNewS/node_modules/nativescript-plugin-firebase/index"'.

node_modules/nativescript-plugin-firebase/firebase.d.ts(699,1): error TS1036: Statements are not allowed in ambient contexts.
```
I am running nativescript version 3.4.2

**Comment by EddyVerbruggen** [comment] 2018-04-26 17:00
The title is a literal duplicate of #685.

Pin your dependency to anything lower than 5.3.0 and you're good.

**Closed by EddyVerbruggen** 2018-04-26 17:00 UTC
