### ISSUE TITLE
Build failed on tns run android

### ISSUE THREAD

**Issue by LakshmiEvana** [EddyVerbruggen/nativescript-plugin-firebase#171] opened 2016-10-14 03:57 UTC
HI,
After adding firebase plugin I'm getting following error when I'm trying to build my app by using tns run android command.

Error -
Command E:\Native Script\firebasetest3\platforms\android\gradlew.bat failed with
exit code 1
Help me please!

**Comment by EddyVerbruggen** [comment] 2016-10-16 08:08
Can you please provide some more info? A stacktrace would be helpful.

Without more details I simply have to say: make sure you've followed all details and tips in the readme.

**Comment by dameety** [comment] 2016-10-23 23:26
@EddyVerbruggen  and @LakshmiEvana

**Comment by ADjenkov** [comment] 2016-10-29 09:18
Same here , I'm using {N} 2.3.0 ...The Build fails for android, even the demo app fails with the same build.gradle error

**Comment by dameety** [comment] 2016-11-03 01:01
In your SDK manager, update your Google play services and Google repository to the latest version, after, remove and add the platforms folder. Now it will work.

**Comment by ADjenkov** [comment] 2016-11-03 06:51
Nope, I've tried that in first place. Using my firebase database through REST API for now.

**Comment by dameety** [comment] 2016-11-05 04:21
Yes the problem is surely with your android sdk. Anyway, the method above worked for me.

**Comment by dxshindeo** [comment] 2016-11-07 19:08
hmm damnit, same problem here, sdk's already up-to-date :/

**Comment by dxshindeo** [comment] 2016-11-10 07:30
Slowly closing in on the issue - build fails when I add `"nativescript-google-maps-sdk": "^1.3.14",` plugin to the project.

**Comment by dxshindeo** [comment] 2016-11-10 08:09
Ooookeeeey, when I check the `node_modules/nativescript-plugin-firebase/platforms/android/include.gradle` file, I see that they are including 9.6.+ version of Firebase in the project, so that's where the error occurs: **Google maps version is "+" (currently 9.8.0), Firebase is "9.6.1".**

So, I have to equalize both those plugin versions. I added the following code in ``App_Resources/Android/app.gradle`` as per https://github.com/dapriett/nativescript-google-maps-sdk :

```
project.ext {
    googlePlayServicesVersion = "9.6.+"
}
```

And that fixed the issue, now project compiles successfully. However, I downgraded the gmaps. It is more logical to upgrade the firebase instead, to match the latest gmaps version, but firebase plugin doesn't have this nice refference that you can make in `App_Resources/Android/app.gradle` as gmaps can, which means, after plugin installation, **you have to manually, on every time you fullly rebuild app (deleting node_modules folder)** go into `node_modules/nativescript-plugin-firebase/platforms/android/include.gradle` and change the versions included to "+" .

Suggestion to Eddy - make that project.ext refference in your plugin, so we don't have to manually change versions every time our node_modules folder has to be recreated.

**Comment by EddyVerbruggen** [comment] 2016-11-13 15:27
Hi @dxshindeo, thanks for the great explanation and suggestion!

I've just pushed the change you suggested to this repo (not on npm yet). Can you please try if this fixes the trouble you had?

**Closed** 2017-06-20 14:04 UTC
