### ISSUE TITLE
Additional Conditional Test Required to Avoid NullPointerException for Method `toLoginResult`

### ISSUE THREAD

**Issue by AjawadMahmoud** [EddyVerbruggen/nativescript-plugin-firebase#816] opened 2018-07-24 10:05 UTC
Hello.

In release version of Nativescript-Android I had to tackle an issue in `toLoginResult` method of `firebase.android.js` in line 902.
The situation was that on the very first run, of my app after a complete fresh install it's crashing, by checking the log I found that it's crashing after getting `null` on call for `user.getMetadata().getCreationTimestamp()`.

The fix is simply adding additional check right before `var loginResult = {` line with:
```
    if (!user.getMetadata()) {
        return null;
    }
```

To verify, I have the following `package.json`:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "my.app.id",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "nativescript-angular": "~6.0.0",
    "nativescript-dev-webpack": "^0.14.4",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-plugin-firebase": "^6.4.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.1.0",
    "tns-core-modules": "~4.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.7.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0-beta.3",
    "@ngtools/webpack": "6.1.0-rc.0"
  }
}
```

**Comment by EddyVerbruggen** [comment] 2018-07-28 10:35
Confirmed, but it's a duplicate of #795.

**Closed by EddyVerbruggen** 2018-07-28 10:35 UTC
Labels: Android, Firebase: Authentication, bug
