### ISSUE TITLE
changes made in listener not reflected in UI

### ISSUE THREAD

**Issue by darkbcx** [EddyVerbruggen/nativescript-plugin-firebase#329] opened 2017-03-23 14:02 UTC
the changes I made in component not reflecting in UI. but it shows when i try to `console.log` it
```
	ngOnInit() {
		firebase.addValueEventListener(
			(result) => {
				console.log("Value: " + JSON.stringify(result.value));
				this.users = result.value;
				console.log('this.users : ', this.users);
				this.test++;
			}, "/users").then(
			(listenerWrapper) => {
				var path = listenerWrapper.path;
				var listeners = listenerWrapper.listeners; // an Array of listeners added
				// you can store the wrapper somewhere to later call 'removeEventListeners'
			});
	}
```

i try to use ngZone but the app crashed.
```
		firebase.addValueEventListener(
			(result) => {
				console.log("Value: " + JSON.stringify(result.value));
				this.zone.run(() => {
					this.users = result.value;
					console.log('this.users : ', this.users);
					this.test++;
				})
			}, "/users").then(
			(listenerWrapper) => {
				var path = listenerWrapper.path;
				var listeners = listenerWrapper.listeners; // an Array of listeners added
				// you can store the wrapper somewhere to later call 'removeEventListeners'
			});
```

with error message like this
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onDataChange failed

[object Object]
File: "file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js, line: 227, column: 12

StackTrace: 
  Frame: function:'SafeSubscriber.__tryOrUnsub', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 227, column: 13
  Frame: function:'SafeSubscriber.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 172, column: 22
  Frame: function:'Subscriber._next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 125, column: 26
  Frame: function:'Subscriber.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subscriber.js', line: 89, column: 18
  Frame: function:'Subject.next', file:'file:///data/data/com.bagubagu.theclubmobile/files/app/tns_modules/rxjs/Subject.js', line: 55,
```

**Comment by EddyVerbruggen** [comment] 2017-03-23 15:03
Not really a plugin issue, so you may be better of moving this Q to StackOverflow. Anyone here an idea?

**Comment by SBD580** [comment] 2017-03-23 22:34
Running the code in NgZone is the right thing to do and its working - I believe your getting the error from another place caused by the detection cycle triggered by that call. Does the log message getting out on console?

**Comment by darkbcx** [comment] 2017-03-24 05:07
the console shows this
```
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
03-24 01:00:25.701  3040  3040 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
```

the message on my last post was copied from the emulator (Genymotion)

**Comment by manishmlv50** [comment] 2017-03-27 11:04
Even I am facing the same issue. @darkbcx  did you find a solution or why this is happening

**Comment by darkbcx** [comment] 2017-03-27 12:12
just find out the culprit. just like @SBD580 said. the problem is somewhere in my codes. the problem is the error object only shown as `[object Object]`. use try-catch to catch and `console.log` the catched error.

@manishmlv50 , try something like this
```
		firebase.addValueEventListener(
			(result) => {
				try {
					this.zone.run(() => {
						this.users = this.user.userObj2Array(result.value);
						console.dump(this.users);
					})
				} catch (err) {
					console.log(err.toString()); // <== FIND THE ERROR HERE
				}
			}, "/users").then(
			(listenerWrapper) => {
				var path = listenerWrapper.path;
				var listeners = listenerWrapper.listeners; 
			});
```

**Comment by SBD580** [comment] 2017-03-28 20:09
@EddyVerbruggen I think you can close this one

**Closed** 2017-03-28 20:34 UTC
Labels: help wanted, question
