### ISSUE TITLE
Cannot read property 'firebase' of undefined

### ISSUE THREAD

**Issue by karan-patel61** [EddyVerbruggen/nativescript-plugin-firebase#1087] opened 2018-12-23 20:44 UTC
I added the start-up wiring to my app.vue and i got this error:
`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'firebase' of undefined
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 24374, column: 17

StackTrace: 
	Frame: function:'runInit', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 24374, column: 18
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 46720, column: 15
	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68576, column: 15
	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68509, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68343, column: 10
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 65705, column: 21

	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'firebase' of undefined
File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 24374, column: 17

StackTrace: 
	Frame: function:'runInit', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 24374, column: 18
	Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 46720, column: 15
	Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68576, column: 15
	Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68509, column: 20
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 68343, column: 10
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 65705, column: 21

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
	at com.tns.Runtime.callJSMethod(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:967)
	at com.tns.Runtime.callJSMethod(Runtime.java:959)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
	... 11 more
`

**Comment by EddyVerbruggen** [comment] 2018-12-23 20:47
Share a repo and I might take a look..

**Comment by karan-patel61** [comment] 2018-12-23 21:49
https://bitbucket.org/growbusy/growbusy/src/back-end/growbusy/

**Comment by karan-patel61** [comment] 2018-12-24 01:34
I took a look at the vendor.js and the line: 24374 looks like this:
`      com.google.firebase.analytics.FirebaseAnalytics.getInstance(appModule.android.currentContext || com.tns.NativeScriptApplication.getInstance()).setAnalyticsCollectionEnabled(arg.analyticsCollectionEnabled !== false);
`

**Comment by EddyVerbruggen** [comment] 2018-12-24 09:11
@karan-patel61 That repo's master branch doesn't have the Firebase plugin installed. Please tell me EXACTLY what I need to do to reproduce this.

**Comment by karan-patel61** [comment] 2018-12-24 16:49
1. Clone the repo
2. Pull from the back-end branch
3. Run it with `tns run android --emulator --bundle`

**Comment by EddyVerbruggen** [comment] 2018-12-25 13:15
@karan-patel61 That branch doesn't have a `firebase.nativescript.json` file so I have no idea what your Firebase config looks like..

**Comment by karan-patel61** [comment] 2018-12-25 22:59
I have tried to reinstall the firebase plugin and I got the following message:
`$ tns plugin add nativescript-plugin-firebase`

`> nativescript-plugin-firebase@7.6.0 postinstall` `C:\Users\patel\growbusy\growbusy\node_modules\nativescript-plugin-firebase`
`> node postinstall-hooks.js && node scripts/postinstall.js`

`NativeScript Firebase Plugin Installation`
`No existing firebase.nativescript.json config file found and terminal is not interactive! Default configuration will be used.`
`+ nativescript-plugin-firebase@7.6.0`
`added 20 packages in 27.252s`
`Successfully installed plugin nativescript-plugin-firebase.`

How can I obtain the `firebase.nativescript.json` file and where do you recommend I add the file

**Comment by karan-patel61** [comment] 2018-12-26 00:08
I added the `firebase.nativescript.json` manually and reinstalled the firebase plugin:
` tns plugin add nativescript-plugin-firebase`

`> nativescript-plugin-firebase@7.6.0 postinstall` `C:\Users\patel\growbusy\growbusy\node_modules\nativescript-plugin-firebase`
`> node postinstall-hooks.js && node scripts/postinstall.js`

`NativeScript Firebase Plugin Installation`
`Config file exists (firebase.nativescript.json)`
`Successfully created iOS (Pod) file.`
`Successfully created Android (include.gradle) file.`
`Install google-service.json after-prepare copy hook.`
`Install google-service.json before-checkForChanges copy hook.`
`Firebase post install completed. To re-run this script, navigate to the root directory of `nativescript-plugin-firebase` in your `node_modules` folder and run:`npm run config`.`
`+ nativescript-plugin-firebase@7.6.0`
`added 20 packages in 29.035s`
`Successfully installed plugin nativescript-plugin-firebase.`

Then when i ran:
`$ npm run config`

`> nativescript-plugin-firebase@7.6.0 config` `C:\Users\patel\growbusy\growbusy\node_modules\nativescript-plugin-firebase`
`> node scripts/postinstall.js config`

`NativeScript Firebase Plugin Installation`
`No existing firebase.nativescript.json config file found and terminal is not interactive! Default` `configuration will be used.`

I have pushed the changes I've made to the back-end branch. What do you recommend I do?

**Comment by EddyVerbruggen** [comment] 2018-12-26 18:53
Wondering why you see `terminal is not interactive`. Which shell is that, and can you try a different one?

**Comment by Jonarod** [comment] 2019-01-11 03:15
I have the same problem when cloning [this repo](https://github.com/jlooper/picme)... 
Reproduce steps:
```
git clone git@github.com:jlooper/picme.git
npm i
tns run android --bundle
```
I use Genymotion to emulate, but I also get the same error when manually transferring the `debug.apk` (`tns build android --bundle`) to a physical android device.

**Comment by EddyVerbruggen** [comment] 2019-01-11 10:18
@Jonarod That's expected as that project is not using Android: https://github.com/jlooper/picme/blob/2b70772c8a500fed74ed3c4284b955e1e9a9e1b8/firebase.nativescript.json#L3

**Comment by guibot17** [comment] 2019-02-26 23:52
I'm having similar issue when trying to preview my app on my android device:

`TypeError: Cannot read property 'FirebaseAnalytics' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/vendor.js, line: 19306, column: 42

StackTrace:
        Frame: function:'runInit', file:'file:///data/data/org.nativescript.preview/files/app/vendor.js', line: 19306, column: 43
        Frame: function:'Observable.notify', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 110, column: 23
        Frame: function:'notifyLaunch', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 979, column: 17
        Frame: function:'ActivityCallbacksImplementation.setActivityContent', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 909, column: 28
        Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 768, column: 14
        Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1646)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6836)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: com.tns.NativeScriptException:
Calling js method onCreate failed`

Your help is appreciated

**Comment by EddyVerbruggen** [comment] 2019-02-27 20:36
@guibot17 I can't help without you sharing the erroneous project.

**Comment by guibot17** [comment] 2019-02-28 08:04
@EddyVerbruggen I'm just using the sidedrawer from the playground, with a few texfields added to the home page; nothing else.
I followed the instruction as you directed and mark all the entries yes expect for the ios because I'm on windows.
Upon installing the plugin, I wanted to see if could finally write some data to firebase. Unfortunately, I was getting this error when trying to launch the preview on my android.
I switched to using the HTTPClient from Angular for now until this is resolved; it's working.
Please let me know if you have any idea what that could be.

Thanks

**Comment by EddyVerbruggen** [comment] 2019-02-28 08:05
@guibot17 Are you running the plugin inside the Preview app?

**Comment by guibot17** [comment] 2019-02-28 20:18
@EddyVerbruggen Well, I run the code and use the Preview app to see the result on my android.

**Comment by EddyVerbruggen** [comment] 2019-02-28 21:08
I understand, but the Preview app ships with a number of plugins, and this is not one of them.. so indeed that doesn’t work.

**Closed by EddyVerbruggen** 2019-02-28 21:08 UTC

**Comment by xdubx** [comment] 2019-09-21 10:37
@guibot17
> TypeError: Cannot read property 'FirebaseAnalytics' of undefined
I get this error only if you initialize firebase in wrong lifecycle hook.
For example app.js 

`new Vue({

    template: `
        <Frame>
            <Home />
        </Frame>`,

    components: {
        Home
    },
created() {
        firebase.init().then(
            instance => {
                console.log("firebase.init done");
                // cars.load().then((data) => {
                //     this.cars = Object.values(data);
                // })
            },
            error => {
                console.log(`firebase.init error: ${error}`);
            }
        );
       }
}).$start();`

If you call it in the **mounded** hook or later the error not appears.

**Comment by rdlauer** [comment] 2019-09-23 18:37
My solution for this issue was to reconfigure the plugin to generate a new `firebase.nativescript.json` file:

> You can reconfigure the plugin by going to the `node_modules/nativescript-plugin-firebase` and running `npm run config`.
