### ISSUE TITLE
Nativescript - Firebase plugin firing onAuthStateChanged twice

### ISSUE THREAD

**Issue by tonyawad88** [EddyVerbruggen/nativescript-plugin-firebase#100] opened 2016-08-06 14:46 UTC
Hello,

I have the follow function that simply inits firebase and pass in an "onAuthStateChanged" call back function. My "onAuthStateChanged" gets called twice. Can someone please help me identify why?

```
constructor() {
        super();

        //init firebase
        this.initFirebase();
}
private initFirebase(){
        firebase.init({
            onAuthStateChanged: (data)=> { 
                console.log(data.loggedIn ? "Logged in to firebase" : "Logged out from firebase");
                if (data.loggedIn) {
                    console.log('user logged in !!!!'); //this gets fired twice along with the above comment.
                }
            }
        }).then(
        (instance) => {console.log("firebase.init done");},
        (error) => {console.log("firebase.init error: " + error);}
        );
}
```

Thank you !!

**Comment by t-moe** [comment] 2016-08-09 21:00
Nothing wrong with your code. This is a known issue, caused by the firebase library it self.
The firebase dev's however don't really consider this a bug. Read more here: https://github.com/firebase/quickstart-android/issues/80
I'll close this, as there's not much we can do on our side.
If it bothers you, you could simply catch the second event and drop it.

**Closed by t-moe** 2016-08-09 21:00 UTC
